/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}', './worker/**/*.html'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#333345',
        'on-secondary-container': '#b2b3f2',
        'secondary': '#c0c1ff',
        'primary-fixed-dim': '#c0c1ff',
        'tertiary-container': '#d97721',
        'surface-tint': '#c0c1ff',
        'surface-container': '#1e1e2f',
        'primary-fixed': '#e1e0ff',
        'surface-container-high': '#29283a',
        'on-error': '#690005',
        'tertiary-fixed': '#ffdcc5',
        'primary': '#c0c1ff',
        'secondary-fixed': '#e1e0ff',
        'primary-container': '#8083ff',
        'inverse-surface': '#e3e0f8',
        'surface-container-lowest': '#0c0c1d',
        'outline-variant': '#464554',
        'error-container': '#93000a',
        'on-secondary-fixed': '#13144a',
        'tertiary': '#ffb783',
        'on-surface-variant': '#c7c4d7',
        'inverse-on-surface': '#2f2f40',
        'secondary-container': '#42447b',
        'on-primary': '#1000a9',
        'on-background': '#e3e0f8',
        'error': '#ffb4ab',
        'on-primary-fixed': '#07006c',
        'surface-container-highest': '#333345',
        'on-primary-fixed-variant': '#2f2ebe',
        'outline': '#908fa0',
        'on-error-container': '#ffdad6',
        'surface-container-low': '#1a1a2b',
        'on-tertiary-fixed': '#301400',
        'secondary-fixed-dim': '#c0c1ff',
        'surface-bright': '#38374a',
        'on-surface': '#e3e0f8',
        'on-secondary-fixed-variant': '#404178',
        'on-tertiary-fixed-variant': '#703700',
        'on-primary-container': '#0d0096',
        'background': '#121222',
        'surface': '#121222',
        'inverse-primary': '#494bd6',
        'on-tertiary': '#4f2500',
        'on-secondary': '#292a60',
        'tertiary-fixed-dim': '#ffb783',
        'surface-dim': '#121222',
        'on-tertiary-container': '#452000',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Inter'],
        body: ['Inter'],
        label: ['Space Grotesk'],
      },
    },
  },
  plugins: [],
}
